import { it, expect, vi } from 'vitest';
import { createMerchantGameRuntime } from '../js/core/MerchantGameRuntime.js';
import { createInitialState } from '../js/data/constants.js';
import * as Merchant from '../js/systems/merchant/MerchantSystem.js';
const plan = { from:'sol_prime',to:'mineral_belt',goodId:'food',shipIds:['ship-1'],budget:220 };
it('隐藏页面按真实轮次结算，停机不会写回旧会话，恢复不会重复结算',()=>{
  let now=1_800_000_000_000;
  let state=createInitialState();Merchant.init(state,now);
  const doc=new EventTarget(),win=new EventTarget(),save=vi.fn(()=>({ok:true})),render=vi.fn();
  const runtime=createMerchantGameRuntime({getState:()=>state,save,render,now:()=>now,documentSource:doc,windowSource:win});
  runtime.start();expect(runtime.execute('create',plan).ok).toBe(true);
  render.mockClear();doc.hidden=true;now+=60000;doc.dispatchEvent(new Event('visibilitychange'));
  expect(state.merchant.tasks).toHaveLength(0);
  expect(state.merchant.history[0]).toMatchObject({rounds:3,profit:126,available:220,stopping:true});
  expect(state.merchant.history[0].stopReason).toContain('无货');
  expect(state.credits).toBe(1126);
  expect(state.merchant.ships[0]).toMatchObject({phase:'idle',taskId:null});
  expect(render).not.toHaveBeenCalled();
  const cash=state.credits;doc.hidden=false;doc.dispatchEvent(new Event('visibilitychange'));expect(state.credits).toBe(cash);
  runtime.stop();save.mockClear();win.dispatchEvent(new Event('pagehide'));runtime.tick(true);expect(save).not.toHaveBeenCalled();
  expect(runtime.execute('create',plan).ok).toBe(false);
  state=createInitialState();Merchant.init(state,now);runtime.start();expect(state.merchant.tasks).toHaveLength(0);runtime.stop();
});
it('操作保存失败提示导出，资源不会重复分配',()=>{
  const now=1_800_000_000_000,state=createInitialState();Merchant.init(state,now);
  const runtime=createMerchantGameRuntime({getState:()=>state,save:()=>({ok:false}),render(){},now:()=>now});runtime.start();
  expect(runtime.execute('create',plan).msg).toContain('存档失败');expect(runtime.execute('create',plan).ok).toBe(false);runtime.stop();
});
it('探索在后台按真实时间返港开港，重复恢复和已停止会话不重复发放',()=>{
  let now=1_800_000_000_000;
  const state=createInitialState();state.merchant.companyLevel=2;state.merchant.exploration.rngState=42;Merchant.init(state,now);
  const doc=new EventTarget(),win=new EventTarget(),save=vi.fn(()=>({ok:true})),render=vi.fn();
  const runtime=createMerchantGameRuntime({getState:()=>state,save,render,now:()=>now,documentSource:doc,windowSource:win});
  runtime.start();now=state.merchant.exploration.nextEventAt;runtime.tick(true);
  expect(runtime.execute('explore',{eventId:state.merchant.exploration.event.id,shipId:'ship-1'}).ok).toBe(true);
  const finalAt=state.merchant.exploration.event.arriveAt+state.merchant.exploration.event.legMs;
  render.mockClear();doc.hidden=true;now=finalAt-1;doc.dispatchEvent(new Event('visibilitychange'));
  expect(state.merchant.unlockedPorts).not.toContain('nebula_forge');
  expect(state.merchant.ships[0].phase).toBe('explore_return');
  now=finalAt;doc.dispatchEvent(new Event('visibilitychange'));
  expect(state.merchant.unlockedPorts).toContain('nebula_forge');
  expect(state.merchant.ships[0]).toMatchObject({phase:'idle',taskId:null});
  expect(state.credits).toBe(640);expect(render).not.toHaveBeenCalled();
  const event=structuredClone(state.merchant.exploration.event);
  doc.hidden=false;doc.dispatchEvent(new Event('visibilitychange'));
  expect(state.merchant.exploration.event).toEqual(event);expect(state.credits).toBe(640);
  runtime.stop();save.mockClear();win.dispatchEvent(new Event('pagehide'));runtime.tick(true);
  expect(save).not.toHaveBeenCalled();expect(state.merchant.exploration.event).toEqual(event);
});
